version: "3.4"

services:
  sql-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    restart: always
    ports: 
      - 1433:1433
    container_name: sql-server
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=RJYQmPo&v%b%k5s
    volumes:
      - ./data:/var/opt/mssql/data
  adminer:
    image: adminer
    container_name: adminer-service
    restart: always
    ports:
      - 8080:8080
  pup-api:
    container_name: pug-planner-api
    image: pup-api:latest
    depends_on:
      - sql-db
    ports:
      - 7066:80
      - 7067:443
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=7067
      - ASPNETCORE_Kestrel__Certificates__Default__Password=selfsignedpw
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - ~/.aspnet/https:/https:ro
