version: "3.4"

services:
  pup-api:
        build:
            dockerfile: Dockerfile
        ports:
            - "8020:80"
        depends_on:
            - sql-db
        volumes:
            - ./src:/app
  sql-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql-server
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=RJYQmPo&v%b%k5s
    volumes:
      - ./data:/var/opt/mssql/data