CREATE TABLE IF NOT EXISTS
  positions (
    id INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    full_name VARCHAR(50) NOT NULL
  );

CREATE TABLE IF NOT EXISTS
  pronouns (
    id INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
  );

CREATE TABLE IF NOT EXISTS
  profiles (
    id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    club VARCHAR(50),
    "admin" BOOLEAN NOT NULL,
    create_date_time TIMESTAMP WITH TIME ZONE NOT NULL,
    primary_position_id INTEGER REFERENCES public.positions ON DELETE CASCADE NOT NULL,
    secondary_position_id INTEGER REFERENCES public.positions ON DELETE CASCADE NOT NULL,
    pronoun_id INTEGER REFERENCES public.pronouns ON DELETE CASCADE,
    emergency_name VARCHAR(50) NOT NULL,
    emergency_phone VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL
  );

CREATE TABLE IF NOT EXISTS
  games (
    id INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    "location" VARCHAR(50) NOT NULL,
    "address" VARCHAR(255) NOT NULL,
    "description" VARCHAR(2040) NOT NULL,
    game_date TIMESTAMP WITH TIME ZONE NOT NULL,
    signup_date TIMESTAMP WITH TIME ZONE NOT NULL,
    max_players INTEGER NOT NULL,
    recurring BOOLEAN NOT NULL,
    primary_host_id uuid REFERENCES public.profiles ON DELETE CASCADE NOT NULL,
    secondary_host_id uuid REFERENCES public.profiles ON DELETE CASCADE NOT NULL
  );

CREATE TABLE IF NOT EXISTS
  game_roster (
    id INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
    game_id INTEGER REFERENCES public.games ON DELETE CASCADE NOT NULL,
    user_profile_id uuid REFERENCES public.profiles ON DELETE CASCADE NOT NULL
  );